# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Player.find_or_create_by({sport: 'NFL', name: 'Peyton Manning', position: 'QB', salary: '9200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Matthew Stafford', position: 'QB', salary: '8800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Eli Manning', position: 'QB', salary: '7500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Blake Bortles', position: 'QB', salary: '5200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Matt Ryan', position: 'QB', salary: '8100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Geno Smith', position: 'QB', salary: '6700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Carson Palmer', position: 'QB', salary: '7200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Tom Brady', position: 'QB', salary: '6600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Russell Wilson', position: 'QB', salary: '7600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Kirk Cousins', position: 'QB', salary: '6500', site: 'fanduel'})

Player.find_or_create_by({sport: 'NFL', name: 'Jamaal Charles', position: 'RB', salary: '7600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Giovani Bernard', position: 'RB', salary: '6700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Fred Jackson', position: 'RB', salary: '4500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Rashad Jennings', position: 'RB', salary: '5500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Lesean Mccoy', position: 'RB', salary: '7800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Demarco Murray', position: 'RB', salary: '7500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Deangelo Williams', position: 'RB', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Frank Gore', position: 'RB', salary: '5200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Carlos Hyde', position: 'RB', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Legarrette Blount', position: 'RB', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Ben Tate', position: 'RB', salary: '5000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Mark Ingram', position: 'RB', salary: '5000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Toby Gerhart', position: 'RB', salary: '4800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Stevan Ridley', position: 'RB', salary: '4300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Ahmad Bradshaw', position: 'RB', salary: '4000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Shonn Greene', position: 'RB', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Darren Sproles', position: 'RB', salary: '5100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Alfred Morris', position: 'RB', salary: '5300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Doug Martin', position: 'RB', salary: '6100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Bishop Sankey', position: 'RB', salary: '4700', site: 'fanduel'})

Player.find_or_create_by({sport: 'NFL', name: 'Calvin Johnson', position: 'WR', salary: '8200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Steve Smith', position: 'WR', salary: '6000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Vincent Jackson', position: 'WR', salary: '5900', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Golden tate', position: 'WR', salary: '4900', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Wes Welker', position: 'WR', salary: '5500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Michael Floyd', position: 'WR', salary: '5300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Mohamed Sanu', position: 'WR', salary: '4700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'John Brown', position: 'WR', salary: '4500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Riley Cooper', position: 'WR', salary: '3900', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Torrey Smith', position: 'WR', salary: '4800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jeremy Maclin', position: 'WR', salary: '5600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Julio Jones', position: 'WR', salary: '8000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Victor Cruz', position: 'WR', salary: '5800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Sammy Watkins', position: 'WR', salary: '4800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Tavon Austin', position: 'WR', salary: '4000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jordan Matthews', position: 'WR', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Brandon Lloyd', position: 'WR', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Miles Austin', position: 'WR', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Stevie Johnson', position: 'WR', salary: '3300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Kenny Stills', position: 'WR', salary: '3700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Doug Baldwin', position: 'WR', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Marvin Jones', position: 'WR', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jeremy Kerley', position: 'WR', salary: '3300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Marqise Lee', position: 'WR', salary: '3200', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Robert Woods', position: 'WR', salary: '3100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Harry Douglas', position: 'WR', salary: '3600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Desean Jackson', position: 'WR', salary: '4600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Pierre Garcon', position: 'WR', salary: '5600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Julian Edelman', position: 'WR', salary: '5700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Dez Bryant', position: 'WR', salary: '7800', site: 'fanduel'})

Player.find_or_create_by({sport: 'NFL', name: 'Travis kelce', position: 'TE', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Antonio Gates', position: 'TE', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Zach Ertz', position: 'TE', salary: '3800', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jimmy Graham', position: 'TE', salary: '7600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Larry Donnell', position: 'TE', salary: '5700', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Greg Olsen', position: 'TE', salary: '5300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jared Cook', position: 'TE', salary: '3300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Mike Leach', position: 'TE', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Dante Rosario', position: 'TE', salary: '3000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Anthony Fasano', position: 'TE', salary: '3000', site: 'fanduel'})

Player.find_or_create_by({sport: 'NFL', name: 'Shayne Graham', position: 'K', salary: '3600', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Patrick Murray', position: 'K', salary: '3100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Matt Bryant', position: 'K', salary: '2800', site: 'fanduel'})

Player.find_or_create_by({sport: 'NFL', name: '49ers', position: 'D', salary: '3500', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Eagles', position: 'D', salary: '3300', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Jaguars', position: 'D', salary: '2000', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Rams', position: 'D', salary: '2100', site: 'fanduel'})
Player.find_or_create_by({sport: 'NFL', name: 'Ravens', position: 'D', salary: '2300', site: 'fanduel'})

